POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Aidan Gillen",
    "number": "040-33083425"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Ada Lovelace",
    "number": "040-33083425"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Graham Norton",
    "number": ""
}
